### ISSUE TITLE
cannot install the node-red-contrib-ads1x15

### ISSUE THREAD

**Issue by albertstuder** [cinqueon/node-red-contrib-ads1x15#7]
Hello I tried several times to install this node. But only this output.
npm version 6.7.0 nodejs version 10.15.1 node-red version 0.19.5
any solution?

pi@raspberrypi:~/.node-red $ npm install node-red-contrib-ads1x15
npm WARN deprecated coffee-script@1.9.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> i2c@0.2.3 install /home/pi/.node-red/node_modules/i2c
> node-gyp rebuild

make: Verzeichnis „/home/pi/.node-red/node_modules/i2c/build“ wird betreten
  CXX(target) Release/obj.target/i2c/src/i2c.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/i2c.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/i2c.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:817:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/i2c.cc:1:0:
/home/pi/.node-gyp/10.15.1/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/pi/.node-gyp/10.15.1/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/i2c.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../src/i2c.cc:1:0:
/home/pi/.node-gyp/10.15.1/include/node/node.h:170:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/pi/.node-gyp/10.15.1/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/i2c.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:845:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../src/i2c.cc:1:0:
/home/pi/.node-gyp/10.15.1/include/node/node.h:163:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/pi/.node-gyp/10.15.1/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/i2c.cc:3:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1463:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/i2c.cc:1:0:
/home/pi/.node-gyp/10.15.1/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/pi/.node-gyp/10.15.1/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/i2c.cc: In function ‘void SetAddress(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:38:30: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   addr = info[0]->Int32Value();
                              ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc: In function ‘void Open(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:84:35: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value device(info[0]);
                                   ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc: In function ‘void Read(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:103:33: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int len = info[0]->Int32Value();
                                 ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc: In function ‘void ReadBlock(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:154:36: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int8_t cmd = info[0]->Int32Value();
                                    ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc:155:37: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int32_t len = info[1]->Int32Value();
                                     ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc:178:43: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       int32_t delay = info[2]->Int32Value();
                                           ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc: In function ‘void Write(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:193:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int   len = node::Buffer::Length(buffer->ToObject());
                                                     ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/node.h:63:0,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/i2c.cc:194:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   char* data = node::Buffer::Data(buffer->ToObject());
                                                    ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/node.h:63:0,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/i2c.cc: In function ‘void WriteByte(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:213:37: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int8_t byte = info[0]->Int32Value();
                                     ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc: In function ‘void WriteBlock(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:232:36: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int8_t cmd = info[0]->Int32Value();
                                    ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc:233:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int   len = node::Buffer::Length(buffer->ToObject());
                                                     ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/node.h:63:0,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/i2c.cc:234:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   char* data = node::Buffer::Data(buffer->ToObject());
                                                    ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/node.h:63:0,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/i2c.cc: In function ‘void WriteWord(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/i2c.cc:253:36: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int8_t cmd = info[0]->Int32Value();
                                    ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/i2c.cc:254:38: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int16_t word = info[1]->Int32Value();
                                      ^
In file included from /home/pi/.node-gyp/10.15.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/10.15.1/include/node/node.h:63,
                 from ../src/i2c.cc:1:
/home/pi/.node-gyp/10.15.1/include/node/v8.h:2478:46: note: declared here
   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
                                              ^
/home/pi/.node-gyp/10.15.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
i2c.target.mk:99: die Regel für Ziel „Release/obj.target/i2c/src/i2c.o“ scheiterte
make: *** [Release/obj.target/i2c/src/i2c.o] Fehler 1
make: Verzeichnis „/home/pi/.node-red/node_modules/i2c/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/i2c
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-01T14_52_43_028Z-debug.log

**Comment by jupiter8888** [comment]
Same here, anyone has a solution?

**Comment by girzol** [comment]
Same here. Node-red 1.0.3, Node.js v.10.15.2
Would be nice to have any help

**Comment by meeki007** [comment]
I made a solution for raspberry pi's 

https://flows.nodered.org/node/node-red-contrib-anolog-to-digital-converter-raspberry-pi
